[tool.poetry]
name = "diagrams-demo"
version = "0.1.0"
description = ""
authors = ["Derek Zoladz <derek@derekzoladz.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
diagrams = "^0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
